### ISSUE TITLE
Need introduction

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/ldml-keyboards-dev#1]
I am curious with this project.

I understand ldml layouts are installable out of box in mac.

does other OS support ldml layouts yet?

can we submit new layouts to unicode consortium for distribution?

**Comment by mhosken** [comment]
There are not actual keyboard implementations yet based on LDML, but they will come. Yes you can propose new layouts for inclusion in CLDR using standard CLDR contribution mechanisms (raise a bug).
