### ISSUE TITLE
Competing Simple Transforms

### ISSUE THREAD

**Issue by Richard57** [keymanapp/ldml-keyboards-dev#2]
There's a fault in the handling of 'simple' transforms in ldml_keyboards.py.  It doesn't handle competing transforms when one is a prefix of the other.  The LDML specifivation (Version 35) defines the behaviour in Section 5.18 with the examples 'ab', 'abc' and 'abd'.

I found a real-life example with my XSAMPA keyboard.  Starting from an ASCII keyboard, I added the transforms  <transforms type="simple">
```
<transforms type="simple">
    <!--transform from="B" to="β"/--> <!-- U+03b2 GREEK SMALL LETTER BETA -->
    <transform from="B\\" to="ʙ"/> <!-- U+0299 LATIN LETTER SMALL CAPITAL B -->
    <transform from="B\\\\" to = "B"/>
    <!--transform from="a~" to = "a\u0303"/--><!--to="ã"/--> <!-- U+00E3 LATIN SMALL LETTER A WITH TILDE -->
     <transform from="A\\_._F" to="Ậ"/> <!-- U+1EAC LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW -->
</transforms>
```
and tried the input
```
[shift B05][C12][C12][C12][C12]
[shift C01][C12][shift E11][B09][shift E11][shift C04][BKSP]

```
I defined no settings element.

I got
```
B, ʙ, ʙ\, ʙ\\, ʙ\\\
A, A\, A\_, A\_., A\_._, Ậ, 
```
The transform of the 2-character sequence "B\\" is applied without waiting to see if the longer 3-element sequence "B\\\\" is input.  The much longer 6-character input sequence "A\\_._F" was handled correctly.  Incidentally, the input handler chokes on redundant backslashes, as can be seen by deleting one of the backslashes from the last of the 'simple' transforms. 

The problem is that the transformations seems to be being applied in the KMfL fashion, whereby matches are taken as soon as input, rather than the scheme used in the related Emacs MULE and M17n keyboards, which look for the longest match before committing the conversion.

**Comment by Richard57** [comment]
I've raised a related issue on the LDML specification, https://unicode-org.atlassian.net/browse/CLDR-13343, as it seems that the behaviour I'm complaining of is preferred by some.  There is the issue that for a US International keyboard, strokes C11, A03, D03 yields apostrophe followed by 'e', whereas the current behaviour of this keyboard model yields 'e' following by combining acute accent.

**Comment by mhosken** [comment]
This issue is included in tests/test1.ldml and tests/tests1_1.xml and should be working correctly now. Notice that this final backspace is not tested since there is no backspace transforms in the keyboard to know what to do with the output sequence (and the default action would be to delete the last component from the compound character).
